# Generated by Django 5.2.1 on 2025-11-29 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_achievement_educationalcontent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraseCompletar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frase_completa', models.TextField(help_text='Frase completa con la palabra clave')),
                ('palabra_clave', models.CharField(help_text='Palabra o frase que se oculta', max_length=200)),
                ('categoria', models.CharField(default='general', help_text='Categoría de la frase', max_length=100)),
                ('nivel_dificultad', models.IntegerField(default=1, help_text='1=fácil, 2=medio, 3=difícil')),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PuntajeCompletarFrases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_total', models.IntegerField(default=0)),
                ('frases_completadas', models.IntegerField(default=0)),
                ('respuestas_correctas', models.IntegerField(default=0)),
                ('respuestas_parciales', models.IntegerField(default=0)),
                ('respuestas_incorrectas', models.IntegerField(default=0)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile')),
            ],
            options={
                'unique_together': {('user',)},
            },
        ),
    ]
