# Generated by Django 5.2.1 on 2025-11-29 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_frasecompletar_puntajecompletarfrases'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialcompetencyassessment',
            options={'ordering': ['-fecha_evaluacion']},
        ),
        migrations.AddField(
            model_name='financialcompetencyassessment',
            name='numero_evaluacion',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='financialcompetencyassessment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_assessments', to='myapp.userprofile'),
        ),
    ]
