# Generated by Django 5.2.1 on 2025-11-30 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_financialcompetencyassessment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PregeneradaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preguntas_evaluacion', models.JSONField()),
                ('preguntas_brecha', models.JSONField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usada', models.BooleanField(default=False)),
                ('fecha_uso', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregeneradas_evaluaciones', to='myapp.userprofile')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PregeneradaFraseCompletar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frase_completa', models.TextField()),
                ('palabra_clave', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usada', models.BooleanField(default=False)),
                ('fecha_uso', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregeneradas_frases', to='myapp.userprofile')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
