# Generated by Django 5.2.1 on 2025-11-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_pregeneradaevaluacion_pregeneradafrasecompletar'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraudpreventioncontent',
            name='visualizaciones',
            field=models.IntegerField(default=0),
        ),
    ]
